from colorama import Fore

def show_help():

    print(Fore.CYAN + "╔════════════════════════════════════════════════════════════════╗")
    print(Fore.CYAN + "║            PLASC0Y Security Framework - Usage Guide            ║")
    print(Fore.CYAN + "╚════════════════════════════════════════════════════════════════╝\n")
    
    print(Fore.CYAN + "Usage:")
    print("  python plascoy.py -u <target> [options]\n")

    print(Fore.YELLOW + "Core Options:")
    print("  -u, --url <target>  Target URL or domain (required)")
    print("  -h, --help          Show this help message")
    print("  --verbose           Enable verbose output\n")

    print(Fore.YELLOW + "SSL/TLS Scanning:")
    print("  --tls               Scan TLS versions and ciphers")
    print("  --testssl           Run comprehensive SSL/TLS test (requires testssl.sh)\n")

    print(Fore.YELLOW + "Network Scanning:")
    print("  --ports             Port scan (1-1024)")
    print("  --dns               DNS enumeration")
    print("  --subdomain         Subdomain enumeration")
    print("  --whois             WHOIS lookup\n")

    print(Fore.YELLOW + "Web Application Scanning:")
    print("  --tech              Detect technologies & frameworks")
    print("  --headers           Analyze security headers")
    print("  --dirbrute          Directory brute force")
    print("  --webvuln           Web vulnerability scan")
    print("  --vuln              General vulnerability scan\n")

    print(Fore.YELLOW + "Vulnerability Scanning:")
    print("  --sqli              SQL Injection scan")
    print("  --xss               Cross-Site Scripting scan")
    print("  --csrf              CSRF scan")
    print("  --lfi               LFI/RFI scan")
    print("  --cmdinj            Command injection scan")
    print("  --redirect          Open redirect scan")
    print("  --upload            File upload vulnerability scan")
    print("  --cors              CORS misconfiguration scan")
    print("  --hostheader        Host header injection scan")
    print("  --ssrf              SSRF scan")
    print("  --xxe               XXE injection scan")
    print("  --deserial          Deserialization scan")
    print("  --api               API vulnerability scan")
    print("  --cve               CVE checker\n")

    print(Fore.YELLOW + "Advanced Vulnerability Scanning (NEW):")
    print("  --ssti              SSTI (Server-Side Template Injection)")
    print("  --idor              IDOR (Insecure Direct Object Reference)")
    print("  --jwt               JWT token analysis")
    print("  --http-methods      HTTP methods analysis")
    print("  --dirlisting        Directory listing detection")
    print("  --backup            Backup files discovery")
    print("  --git               .git repository exposure")
    print("  --env               Environment files exposure")
    print("  --robots            Robots.txt analysis")
    print("  --sitemap           Sitemap analysis")
    print("  --clickjacking      Clickjacking vulnerability scan")
    print("  --cors-adv          Advanced CORS misconfiguration")
    print("  --params            Parameter mining")
    print("  --js                JavaScript analysis")
    print("  --cookies           Cookie security analysis\n")

    print(Fore.YELLOW + "CMS & Infrastructure:")
    print("  --cms               CMS detection")
    print("  --os                OS fingerprinting")
    print("  --services          Service detection")
    print("  --firewall          Firewall detection")
    print("  --db                Database vulnerability scan\n")

    print(Fore.YELLOW + "External Tools (NEW):")
    print("  --gobuster          Run Gobuster (directory brute force)")
    print("  --ffuf              Run ffuf (fast fuzzing)")
    print("  --nmap              Run Nmap (port scanning)")
    print("  --whatweb           Run WhatWeb (technology detection)\n")

    print(Fore.YELLOW + "Advanced Features (NEW):")
    print("  --crawl             Web crawler (discover endpoints)")
    print("  --fuzz <type>       Fuzzing (xss, sqli, lfi, xxe, all, random)")
    print("  --threads <n>       Number of threads (default: 10)")
    print("  --output <format>   Export report (json, html, csv, txt)")
    print("  --report            Generate built-in report summary")
    print("  --report-gen        Create JSON report with findings")
    print("  --external          Run available external tools (gobuster, ffuf, nmap, whatweb)")
    print("  --recon             Run recon suite: dns, subdomain, whois, headers, tech detection")
    print("  --audit             Run fast audit of critical web vulnerabilities\n")

    print(Fore.YELLOW + "Aggregate Scans:")
    print("  --all               Run full comprehensive scan\n")

    print(Fore.GREEN + "Examples:")
    print("  python plascoy.py -u google.com --tls")
    print("  python plascoy.py -u example.com --sqli --xss --csrf")
    print("  python plascoy.py -u target.com --testssl")
    print("  python plascoy.py -u mysite.com --all --verbose")
    print("  python plascoy.py -u target.com --crawl --fuzz xss")
    print("  python plascoy.py -u target.com --output html")
    print("  python plascoy.py -u target.com --recon --report")
    print("  python plascoy.py -u target.com --audit --output html")
    print("  python plascoy.py -u target.com --gobuster --ffuf --nmap\n")

    print(Fore.CYAN + "Notes:")
    print("  • Provide domain with or without protocol (http/https)")
    print("  • testssl.sh feature requires testssl.sh installed")
    print("  • External tools (gobuster, ffuf, nmap, whatweb) must be installed")
    print("  • Use --verbose for detailed output")
    print("  • Use --output to save results in multiple formats")
    print("  • Combine multiple scans for comprehensive testing\n")

